apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitlab-gke-cicd
    version: 1.0.0
  name: gitlab-gke-cicd
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: gitlab-gke-cicd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gitlab-gke-cicd
        version: 1.0.0
    spec:
      containers:
        - image: gcr.io/master-legacy-374203/gitlab-gke-cicd
          imagePullPolicy: IfNotPresent
          name: gitlab-gke-cicd
          ports:
            - name: tomcat-port
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: tomcat-port
            failureThreshold: 5
            periodSeconds: 5
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: tomcat-port
            failureThreshold: 5
            periodSeconds: 5
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab-gke-cicd
    version: 1.0.0
  name: gitlab-gke-cicd
spec:
  ports:
    - name: service-port
      port: 80
      targetPort: 8080
      nodePort: 32671
      protocol: TCP
  selector:
    app: gitlab-gke-cicd
    version: 1.0.0
  type: NodePort

